do $$declare f alb_fixture;r jsonb;again jsonb;op uuid:=gen_random_uuid();req jsonb;d1 jsonb;d2 jsonb;before_count bigint;begin
 select * into f from alb_fixture;
 select document into d1 from public.travel_book_composition_versions where composition_id=f.c1 and version=1;
 req:=jsonb_build_array(jsonb_build_object('expected_version',1,'document',jsonb_set(d1,'{metadata,label}','"first"')));
 r:=public.save_travel_book_compositions_v1(f.trip,f.book,f.edition,op,req);
 perform pg_temp.assert_alb(r#>>'{compositions,0,version}'='2','CAS increments integer version');
 perform set_config('request.jwt.claim.sub',f.b::text,true);
 perform pg_temp.alb_save(f.c1,2,'member B');
 perform set_config('request.jwt.claim.sub',f.a::text,true);
 again:=public.save_travel_book_compositions_v1(f.trip,f.book,f.edition,op,req);
 perform pg_temp.assert_alb(again-'replayed'=r-'replayed' and again->>'replayed'='true','replay returns ORIGINAL result after later member edit');
 perform pg_temp.assert_alb(public.get_travel_book_operation_v1(op)=again,'receipt retrieval');
 perform pg_temp.expect_alb_error(format('select pg_temp.alb_save(%L,3,%L,%L)',f.c1,'different request',op),'22023');
 perform pg_temp.expect_alb_error(format('select pg_temp.alb_save(%L,1,%L)',f.c1,'stale'),'40001');
 select count(*) into before_count from public.travel_book_operations;
 select document into d1 from public.travel_book_composition_versions where composition_id=f.c1 and version=3;
 select document into d2 from public.travel_book_composition_versions where composition_id=f.c2 and version=1;
 req:=jsonb_build_array(jsonb_build_object('expected_version',3,'document',jsonb_set(d1,'{metadata,label}','"atomic"')),jsonb_build_object('expected_version',99,'document',d2));
 perform pg_temp.expect_alb_error(format('select public.save_travel_book_compositions_v1(%L,%L,%L,%L,%L)',f.trip,f.book,f.edition,gen_random_uuid(),req),'40001');
 perform pg_temp.assert_alb((select current_version=3 from public.travel_book_compositions where id=f.c1),'multi-save rolls back all');
 perform pg_temp.assert_alb((select count(*)=before_count from public.travel_book_operations),'failure stores no receipt');
 req:=jsonb_build_array(jsonb_build_object('expected_version',3,'document',d1));
 perform public.save_travel_book_compositions_v1(f.trip,f.book,f.edition,gen_random_uuid(),req);
 perform pg_temp.assert_alb((select current_version=3 from public.travel_book_compositions where id=f.c1),'no-op creates no redundant version');
 perform pg_temp.expect_alb_error(format('select public.change_travel_book_structure_v1(%L,%L,%L,%L,1,%L,%L,%L)',f.trip,f.book,f.edition,gen_random_uuid(),'[]','{}',array[f.c2,f.c1]),'40001');
 perform public.change_travel_book_structure_v1(f.trip,f.book,f.edition,gen_random_uuid(),2,'[]','{}',array[f.c2,f.c1]);
 perform pg_temp.assert_alb((select array_agg(id order by position)=array[f.p2,f.p3,f.p1] from public.travel_book_pages where edition_id=f.edition),'spread reorders as consecutive unit');
 perform pg_temp.expect_alb_error(format('select public.change_travel_book_structure_v1(%L,%L,%L,%L,3,%L,%L,%L)',f.trip,f.book,f.edition,gen_random_uuid(),'[]','{}',array[f.c2,f.c2]),'22023');
 perform public.change_travel_book_structure_v1(f.trip,f.book,f.edition,gen_random_uuid(),3,'[]',array[f.c2],array[f.c1]);
 perform pg_temp.assert_alb((select count(*)=2 and bool_and(position is null) from public.travel_book_pages where composition_id=f.c2),'remove spread retains both pages');
 perform pg_temp.assert_alb(exists(select 1 from public.travel_book_composition_versions where composition_id=f.c2),'remove retains versions');
 perform pg_temp.expect_alb_error(format('select pg_temp.alb_save(%L,1,%L)',f.c2,'removed'),'P0002');
end$$;
reset role;
rollback;
