import {withBriefTimeout} from './travel-builder.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class HandoffSession{
 constructor(client,owner,storage,isCurrent=()=>true){this.client=client;this.owner=owner;this.storage=storage;this.isCurrent=isCurrent;this.key='freya-handoff-v1:'+owner;this.pending=JSON.parse(storage.getItem(this.key)||'null');this.busy=false;}
 clear(){const stored=JSON.parse(this.storage.getItem(this.key)||'null');if(!stored||stored.p_operation_id===this.pending?.p_operation_id)this.storage.removeItem(this.key);this.pending=null;}
 async read(brief){const {data,error}=await withBriefTimeout(this.client.rpc('get_trip_handoff_v1',{p_brief_id:brief}));if(!this.isCurrent())throw Error('La sessió ha canviat.');if(error)throw error;return data;}
 prepare(row,result,proposal,details){if(this.pending)throw Error('Verifica primer la construcció pendent.');if(row.owner_id!==this.owner||!this.isCurrent())throw Error('La sessió ha canviat.');if(result.stale||result.generation.brief_revision!==row.revision)throw Error('El resum ha canviat. Revisa les alternatives abans de construir.');
 this.pending={p_brief_id:row.id,p_expected_brief_revision:row.revision,p_proposal_id:proposal.id,p_expected_generation_id:result.generation.id,p_expected_snapshot_hash:result.generation.snapshot_hash,p_operation_id:crypto.randomUUID(),p_details:structuredClone(details)};this.storage.setItem(this.key,JSON.stringify(this.pending));}
 async execute(){if(this.busy)return null;if(!this.pending||!this.isCurrent())throw Error('No hi ha cap petició pendent.');this.busy=true;try{
 const command=this.pending;this.storage.setItem(this.key,JSON.stringify(command));const {data,error}=await withBriefTimeout(this.client.rpc(command.p_details.bindings?'formalize_trip_proposal_v2':'formalize_trip_proposal_v1',command));if(!this.isCurrent())throw Error('La sessió ha canviat.');if(error){if(['22023','23514','23503','42501','40001','55000'].includes(error.code))this.clear();throw error;}this.clear();return data;
 }catch(error){if(!this.isCurrent())throw error;if(this.pending){try{const completed=await this.read(this.pending.p_brief_id);if(completed){this.clear();return completed;}}catch{}}throw error;}finally{this.busy=false;}}
}
export function renderHandoffForm(row,result,proposal){
 const cs=proposal.document.candidate.components;
 return `<form id="handoffForm"><h3>Construir aquest viatge</h3><p>Crearàs el viatge amb peces previstes. Això no confirma cap reserva.</p><label>Nom del viatge<input name="name" maxlength="100" required value="${esc(proposal.document.candidate.title.slice(0,100))}"></label><div id="handoffPlaces"></div><label>Data d’inici, opcional<input name="start_date" type="date"></label><label>Data de fi, opcional<input name="end_date" type="date"></label><p>Si encara no tens dates, deixa totes dues buides. Els horaris continuaran per concretar.</p><h4>Peces previstes</h4>${cs.length?cs.map(c=>`<fieldset data-handoff-component="${esc(c.id)}" data-kind="${esc(c.kind)}"><legend>${esc(c.kind==='accommodation'?'Allotjament per concretar':c.kind==='transport'?'Transport per concretar':'Activitat per concretar')}</legend><p>${esc(c.description)}</p>${c.kind==='transport'?'<label>Quin transport és?<select name="target" required><option value="">Tria explícitament</option><option value="flight">Vol</option><option value="transport">Un altre transport</option></select></label>':''}</fieldset>`).join(''):'<p>Aquesta alternativa no conté peces concretes: es crearà només l’espai del viatge.</p>'}<label><input name="acknowledge_unresolved" type="checkbox" required> Entenc que els imprescindibles pendents continuen sense verificar i que no s’està confirmant cap reserva.</label><button type="submit">Crear el viatge amb peces previstes</button><button type="button" id="handoffCancel">Torna al detall</button><p id="handoffMessage" role="status"></p></form>`;
}
export function handoffDetails(form){const data=new FormData(form),components={};form.querySelectorAll('[data-handoff-component]').forEach(el=>{const kind=el.dataset.kind;components[el.dataset.handoffComponent]={target:kind==='transport'?el.querySelector('[name="target"]').value:kind==='accommodation'?'accommodation':'activity'};});return {name:data.get('name').trim(),start_date:data.get('start_date')||null,end_date:data.get('end_date')||null,acknowledge_unresolved:data.get('acknowledge_unresolved')==='on',components};}
