import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {ingest,createIngestHandler,editorialPath} from '../supabase/functions/travel-book-ingest/handler.mjs';
import {photoIngestionRequest,contextSnapshotRequest,editorialReference} from '../domain/travel-book-sources.mjs';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const hash=async b=>createHash('sha256').update(b).digest('hex');
function fixture(){
 const source=new Uint8Array([1,2,3]);const objects=new Map([['trip-documents/source',source]]);const variants=[];
 const asset={id:id(1),trip_id:id(2),book_id:id(3),asset_key:id(4),version:1,status:'pending'};
 const job={source_path:'source',lease_id:id(5),source_hash:null,source_orientation:null};let authorized=true;
 const deps={assetId:asset.id,actor:id(6),auth:'Bearer user',hash,
 inspectSource:bytes=>({mime:'image/jpeg',ext:'jpg',width:20,height:10,orientation:1,byte_size:bytes.length}),
 processImage:async bytes=>({source_hash:await hash(bytes),source_orientation:1,master:{bytes:new Uint8Array([7,8]),width:20,height:10},preview:{bytes:new Uint8Array([7]),width:10,height:5},thumbnail:{bytes:new Uint8Array([8]),width:4,height:2}}),
 storage:{read:async(b,p)=>objects.get(b+'/'+p)||null,put:async(b,p,bytes)=>{if(!objects.has(b+'/'+p))objects.set(b+'/'+p,bytes);}},
 rpc:async(name,p)=>{
  if(!authorized)throw Object.assign(Error('denied'),{code:'42501'});
  if(name==='alb03_claim_v1')return {asset:{...asset},job:{...job},variants:structuredClone(variants)};
  if(p.p_error){asset.status=asset.status==='ready'||['SOURCE_MISSING','MASTER_MISSING'].includes(p.p_error)?'missing':asset.status;return;}
  const d=p.p_descriptor;
  for(const [kind,v] of Object.entries(d)){
   const row={kind,content_hash:v.hash,storage_path:v.path,width_px:v.width,height_px:v.height,mime_type:v.mime,file_extension:v.ext,byte_size:v.byte_size,orientation:v.orientation};
   const previous=variants.find(x=>x.kind===kind);if(previous)assert.deepEqual(row,previous);else variants.push(row);
  }
  if(d.preview)Object.assign(asset,{status:'ready',content_hash:d.preview.hash,storage_path:d.preview.path,storage_bucket:'travel-book',width_px:d.preview.width,height_px:d.preview.height});
  Object.assign(job,{source_hash:d.original.hash,source_orientation:d.original.orientation});
 }};
 return {deps,asset,job,objects,variants,revoke:()=>{authorized=false;}};
}
test('ingestion verified readback, descriptors and idempotent reuse',async()=>{const f=fixture();assert.equal((await ingest(f.deps)).status,'ready');const first=JSON.stringify(f.asset);assert.equal((await ingest(f.deps)).reused,true);assert.equal(JSON.stringify(f.asset),first);assert.equal(f.objects.size,4);assert.equal(editorialReference(f.asset).path,editorialPath(f.asset,'preview'));});
test('source deleted after incorporation retains master and can be reused',async()=>{const f=fixture();await ingest(f.deps);f.objects.delete('trip-documents/source');assert.equal((await ingest(f.deps)).status,'ready');});
test('partial upload failure stays pending; retry reuses insert-only objects',async()=>{const f=fixture();const put=f.deps.storage.put;let fail=true;f.deps.storage.put=async(b,p,bytes)=>{if(p.endsWith('preview.png')&&fail)throw Error('STORAGE_ERROR');await put(b,p,bytes);};assert.equal((await ingest(f.deps)).error,'STORAGE_ERROR');assert.equal(f.asset.status,'pending');fail=false;assert.equal((await ingest(f.deps)).status,'ready');assert.equal(f.objects.size,4);});
test('corrupt readback never marks ready',async()=>{const f=fixture();f.deps.storage.put=async(b,p)=>f.objects.set(b+'/'+p,new Uint8Array([99]));assert.equal((await ingest(f.deps)).error,'STORAGE_ERROR');assert.equal(f.asset.status,'pending');});
test('missing verified master is restored only with identical source and descriptor',async()=>{const f=fixture();await ingest(f.deps);const master=f.variants.find(v=>v.kind==='original').storage_path,hash=f.asset.content_hash;f.objects.delete('travel-book/'+master);assert.equal((await ingest(f.deps)).status,'ready');assert.equal(f.asset.content_hash,hash);f.objects.delete('travel-book/'+master);f.objects.set('trip-documents/source',new Uint8Array([99]));assert.equal((await ingest(f.deps)).error,'MASTER_MISSING');assert.equal(f.asset.status,'missing');assert.equal(f.asset.content_hash,hash);});
test('revocation before finalization cannot mark ready or record an error as the old actor',async()=>{const f=fixture();const put=f.deps.storage.put;f.deps.storage.put=async(...args)=>{await put(...args);f.revoke();};await assert.rejects(ingest(f.deps),{code:'42501'});assert.equal(f.asset.status,'pending');});
test('source absent before ingestion becomes missing without descriptor',async()=>{const f=fixture();f.objects.clear();assert.equal((await ingest(f.deps)).error,'SOURCE_MISSING');assert.equal(f.asset.status,'missing');assert.equal(f.asset.content_hash,undefined);});
test('transport rejects signed URLs, unknown fields and unreviewed free text',()=>{const ids={tripId:id(1),bookId:id(2),documentId:id(3),operationId:id(4)};assert.equal(photoIngestionRequest(ids).args.p_document_id,id(3));assert.throws(()=>photoIngestionRequest({...ids,documentId:'https://x?token=secret'}));const context={...ids,sourceKind:'trip',sourceId:id(1),fields:['label']};assert.throws(()=>contextSnapshotRequest(context),/REVIEW/);assert.throws(()=>contextSnapshotRequest({...context,textReviewed:true,fields:['booking_reference']}),/FIELDS/);assert.equal(contextSnapshotRequest({...context,textReviewed:true}).args.p_text_reviewed,true);assert.throws(()=>editorialReference({status:'ready',storage_bucket:'travel-book',storage_path:'https://x?token=secret',content_hash:'a'.repeat(64)}));});
test('HTTP rejects forged actor/URL, oversized input and unauthenticated callers',async()=>{const f=fixture();const h=createIngestHandler({...f.deps,authenticate:async()=>null});const req=b=>new Request('http://local/',{method:'POST',body:JSON.stringify(b)});assert.equal((await h(req({asset_id:id(1)}))).status,401);assert.equal((await h(req({asset_id:id(1),actor:id(6)}))).status,400);assert.equal((await h(req({asset_id:'https://evil/'}))).status,400);assert.equal((await h(req({asset_id:'x'.repeat(5000)}))).status,400);});

test('original is byte-for-byte, with its own MIME, extension and stable hash',async()=>{const f=fixture();const source=f.objects.get('trip-documents/source');await ingest(f.deps);const original=f.variants.find(v=>v.kind==='original');assert.deepEqual(f.objects.get('travel-book/'+original.storage_path),source);assert.equal(original.content_hash,await hash(source));assert.equal(original.mime_type,'image/jpeg');assert.equal(original.file_extension,'jpg');assert.notEqual(original.content_hash,f.asset.content_hash);});
for(const format of ['heic','heif'])test(`${format} original is durable while derivatives are pending, including retries after source deletion`,async()=>{const f=fixture();f.deps.inspectSource=bytes=>({mime:'image/'+format,ext:format,width:4032,height:3024,orientation:0,byte_size:bytes.length});f.deps.processImage=async()=>{throw Error('DERIVATIVE_UNSUPPORTED');};const r=await ingest(f.deps);assert.equal(r.status,'derivative_pending');assert.equal(r.original_preserved,true);assert.equal(f.asset.status,'pending');assert.equal(f.variants.length,1);assert.equal(f.variants[0].mime_type,'image/'+format);f.objects.delete('trip-documents/source');const size=f.objects.size;assert.equal((await ingest(f.deps)).status,'derivative_pending');assert.equal(f.objects.size,size);assert.equal(f.variants.length,1);});
test('retry after partial derivative failure uses preserved original even if source is deleted',async()=>{const f=fixture();const put=f.deps.storage.put;f.deps.storage.put=async(b,p,data,mime)=>{if(p.endsWith('thumbnail.png'))throw Error('STORAGE_ERROR');return put(b,p,data,mime);};await ingest(f.deps);assert.equal(f.variants.length,1);f.objects.delete('trip-documents/source');f.deps.storage.put=put;assert.equal((await ingest(f.deps)).status,'ready');assert.equal(f.variants.length,3);assert.equal(f.objects.size,3);});
