import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const pointerCode=html.slice(html.indexOf('function builderPointer('),html.indexOf('function builderHistory('));
function harness(){const storage=new Map();const context=vm.createContext({session:{user:{id:'a'}},builderRow:{id:'brief',revision:9,document:{notes:'must not be stored'}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},visibleAppView:()=> 'tripsHomeView',history:{state:null},resumeBuilder:async()=>{},openBuilderProposals:async()=>{}});vm.runInContext(pointerCode,context);return {context,storage};}
test('durable navigation stores exact generation/revision/detail, never content',()=>{const {context,storage}=harness();context.rememberBuilder({generation:'old',revision:2,detail:'proposal',mode:'results',document:{private:'not saved'}});const saved=JSON.parse(storage.get('freya-builder-nav-v1:a'));assert.deepEqual(saved,{active:true,brief:'brief',revision:2,proposal:{brief:'brief',generation:'old',detail:'proposal',mode:'results'}});});
test('intentional Home marks inactive but retains resume location; accounts are isolated',()=>{const {context,storage}=harness();context.rememberBuilder({generation:'g'});context.leaveBuilderPointer();assert.equal(context.builderPointer().active,false);assert.equal(context.builderPointer().proposal.generation,'g');context.session.user.id='b';assert.equal(context.builderPointer(),null);assert.equal(storage.size,1);});
test('corrupt or unavailable local storage never blocks app navigation',()=>{const {context,storage}=harness();storage.set('freya-builder-nav-v1:a','invalid');assert.equal(context.builderPointer(),null);context.localStorage.setItem=()=>{throw Error('denied')};assert.doesNotThrow(()=>context.rememberBuilder());});
test('resume reads saved identifiers without generation, even when summary load updates pointer',async()=>{const {context}=harness();context.rememberBuilder({generation:'old',detail:'detail',mode:'results'});const calls=[];context.resumeBuilder=async id=>{calls.push(id);context.rememberBuilder()};context.openBuilderProposals=async(...args)=>calls.push(args);await context.resumeBuilderPointer();assert.deepEqual(calls,['brief',[false,'detail',false,'old','results']]);});
test('Home header hides contextual email and trip; actual trip detail preserves them',()=>{const nodes={tripTitleTop:{},userEmail2:{}};const context=vm.createContext({$:id=>nodes[id],trip:{name:'Selected trip'},session:{user:{email:'test@example.invalid'}}});vm.runInContext(html.slice(html.indexOf('function renderContextHeader('),html.indexOf('function setAppView(')),context);context.renderContextHeader('tripsHomeView');assert.equal(nodes.tripTitleTop.textContent,'');assert.equal(nodes.userEmail2.textContent,'');context.renderContextHeader('genericDashboardView');assert.equal(nodes.tripTitleTop.textContent,'Selected trip');assert.equal(nodes.userEmail2.textContent,'','The contextual email is intentionally never shown in the trip header');});
